title: Jersey Ann Krupp # your name (or website title) here
logo: "/images/My-project-5.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://www.linkedin.com/in/jersey-ann-krupp/">LinkedIn</a> 
  <br>
  <a href="/pdf/Resume_Krupp,Jersey.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://github.com/JerseyK">GitHub</a>  
  <br>

theme: jekyll-theme-minimal
